name: Update

on:
  push:
    branches:
      - main
  repository_dispatch:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ssh-key: ${{ secrets.SSH_KEY_SEC }}

      - name: Configure git
        shell: bash -euo pipefail {0}
        run: |
          # Configure git
          ssh-agent -a "$SSH_AUTH_SOCK"
          ssh-add - <<< "$SSH_KEY_SEC"
          git config --global user.name "$GIT_USER_NAME"
          git config --global user.email "$GIT_USER_EMAIL"
          git config --global commit.gpgsign true
          git config --global tag.gpgsign true
          git config --global gpg.format ssh
          git config --global user.signingkey "$SSH_KEY_PUB"
        env:
          SSH_KEY_SEC: ${{ secrets.SSH_KEY_SEC }}
          SSH_KEY_PUB: ${{ vars.SSH_KEY_PUB }}
          GIT_USER_NAME: ${{ vars.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ vars.GIT_USER_EMAIL }}

      - name: Install Nix
        uses: cachix/install-nix-action@master
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Cachix
        uses: cachix/cachix-action@master
        with:
          name: ${{ vars.CACHIX_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Update flake inputs
        id: update_flake
        shell: bash -euo pipefail {0}
        run: |
          nix flake update --quiet --no-warn-dirty
          git add flake.lock
          updated=false
          if [ -n "$(git diff --cached)" ]; then
            git commit -m "ci: Update nix flake inputs" -m "[skip actions]"
            updated=true
          fi
          echo "updated=$updated" >> $GITHUB_OUTPUT

      - name: Push updates
        if: steps.update_flake.outputs.updated == 'true'
        run: git push

      - name: Clear SSH agent
        if: always()
        run: ssh-add -D
